name: .NET CI

on: # RD: Let's do this for main only right now -- No reason to overthink this at the moment.'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # RD: Going with 8.0 for long term support.

      - name: Restore dependencies # RD: Crucial -- We want to make sure our dependencies are properly restored for Selenium
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release
